== Getting Started

[#environment]
=== Your Environment

The lab environment consists of four servers and a control node.

image::/images/
-topology.png[role="thumb center" width=80%]

[%header,cols="3,3,2,2,3,5"] 
|===
|Server
|Role
|Ports (TCP)
|Software 
|Ansible Group
|Purpose

| `control`
| Control Node
| 22
| Ansible
| *NA*
| Ansible Control Node

| `frontend`
| Load Balancer
| 22, 80, 443
| HAProxy 
|`load_balancers`
| Load balances across App Tier

| `app-01`, `app-02`
| Application Servers
| 22, 8080
| Python Flask
| `app_servers`
| Webserver and API (Python/Flask)

| `appdb1`
| Database Server
| 22, 5432
| Postgresql
| `database_servers`
| Back end database for Flask application

|===

NOTE: Only `control` and `frontend` are exposed to the Internet

All nodes, today, run Red Hat Enterprise Linux 7 or 8.
At this point, the nodes do not have their respective application payloads installed or configured but are setup for `ssh` access.

You will work, and run, Ansible from the Ansible Control Node `control.example.com`.

[#connect]
=== Connect to your control node

. `ssh` directly to your `control` node. `ssh` is pre-configured via your `~/.ssh` directory
+
[source,sh]
----
ssh control.example.com
----

[#explore]
== Explore your environment

. Check your basic toolchain is in place. At a minimum you will need `ansible` and `git`

+
[source,sh]
----
type git ansible
----
+
.Sample Output
[source,texinfo]
----
git is /bin/git
ansible is /bin/ansible
----

. Install any preferred additional tools, utilities, and configuration you like to have
+

If you expect to spend any significant amount of time working directly on a host it is recommended to spend a few moments customizing your working environment. Possible steps can include:

* Customize your `~/.bashrc` or equivalent
* Customize your `~/.vimrc` or equivalent
* Installs useful and/or favorite tools e.g.:
** vim/emacs/nano
** curl
** telnet # useful for debugging services
** jq     # if you expect to be working with JSON etc
** tree
* Other environment optimizations

[TIP] 
====
Whilst typically not widely used here is a use-case for the `ansible-pull` command that allows you to pull in an external playbook and execute it.
For example create a playbook in a git repo that customizes a typical Linux environment, installs favorite/useful packages and customizes key files such as `~/.bashrc`. 
====

Now your toolchain is in place and optimized move on to exploring your `ansible` setup and lab.

=== Installing your Ansible `git` repo

Your starting point is a fully functional but somewhat monolithic solution available via `git`.
 
. Clone the deployer git repo
+

[source,sh]
----
git clone https://github.com/tonykay/ansible_flask_app_loader_all_in_one.git
----
+
.Sample Output
[source,texinfo]
----
Cloning into 'ansible_flask_app_loader_all_in_one'...
remote: Enumerating objects: 41, done.
remote: Counting objects: 100% (41/41), done.
remote: Compressing objects: 100% (25/25), done.
remote: Total 41 (delta 16), reused 40 (delta 15), pack-reused 0
Unpacking objects: 100% (41/41), done.
----

. Change directory into you project

+
[source,sh]
----
cd ansible_flask_app_loader_all_in_one
----

=== Check your `ansible` configuration and Setup

Typical tasks working with a new, or unfamiliar, control node and repo:

* Check ansible version
* Identify, and examine, your `ansible.cfg`
* Explore your inventory
* Verify your `ssh` setup and configuration

. Check `ansible` version
+
[source,sh]
----
ansible --version
----
+

.Sample Output
[source,texinfo]
----
ansible 2.9.15
  config file = /home/devops/ansible_flask_app_loader_all_in_one/ansible.cfg
  configured module search path = ['/home/devops/.ansible/plugins/modules', '/usr/share/ansible/plugins/
modules']
  ansible python module location = /usr/lib/python3.6/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.6.8 (default, Aug 18 2020, 08:33:21) [GCC 8.3.1 20191121 (Red Hat 8.3.1-5)]
----
+
. Explore your Ansible *inventory*
+

[source,sh]
----
cat hosts
----
+
.Sample Output
[source,texinfo]
----
[load_balancers]
frontend

[app_servers]
app-01
app-02

[database_servers]
appdb1

[ntierapp:children]
load_balancers
app_servers
database_servers
----
+
[TIP]
====
`ansible-inventory` is a useful utility for exploring, and visualizing, your inventory. 

.`ansible-inventory` options
[%header%footer%autowidth]
|===
| Option | Function
| `--graph` | Create an inventory graph, also `--graph <GROUP>` option
| `--vars`  | Adds vars to `--graph` output *only*
| `--host`  | Specific host
| `-i`      | Alternative inventory source
|===

[source,sh]
----
ansible-inventory --graph --vars
----

.Sample Output
[source,texinfo]
----
@all:
  |--@internal:
  |  |--@app_servers:
  |  |  |--app-01
  |  |  |--app-02
  |  |--@database_servers:
  |  |  |--appdb1
  |  |--@load_balancers:
  |  |  |--frontend
  |--@ungrouped:
----
====
+
NOTE: You can also list your inventory groups hosts with the `ansible` command `ansible <GROUP_NAME> --list-hosts` e.g. `ansible all --list-hosts`
The `-i` option allows you to specify an alternative inventory including a directory or dynamic inventory script or plugin.

. Finally verify basic `ssh` connectivity to show that your `ssh` configuration is valid and all necessary users, and keys are setup.
+
[source,sh]
----
ansible all -m ping
----
+
.Sample Output
[source,texinfo]
----
Thursday 07 January 2021  15:43:15 +0000 (0:00:00.050)       0:00:00.050 ****** 
appdb1 | SUCCESS => {
    "ansible_facts": {
        "discovered_interpreter_python": "/usr/bin/python"
    },
    "changed": false,
    "ping": "pong"
}
frontend | SUCCESS => {
    "ansible_facts": {
        "discovered_interpreter_python": "/usr/libexec/platform-python"
    },
    "changed": false,
    "ping": "pong"
}
app-02 | SUCCESS => {
    "ansible_facts": {
        "discovered_interpreter_python": "/usr/libexec/platform-python"
    },
    "changed": false,
    "ping": "pong"
}
app-01 | SUCCESS => {
    "ansible_facts": {
        "discovered_interpreter_python": "/usr/libexec/platform-python"
    },
    "changed": false,
    "ping": "pong"
}
Thursday 07 January 2021  15:43:16 +0000 (0:00:00.712)       0:00:00.762 ****** 
=============================================================================== 
ping ---------------------------------------------------------------------------------------------------------------------------------------------------------------- 0.71s
Playbook run took 0 days, 0 hours, 0 minutes, 0 seconds
----

[NOTE]
====
The different values of `"discovered_interpreter_python":` in the output suggest that not all the nodes are identically configured or perhaps the same version of the Operating System. 
Red Hat Enterprise Linux 7 and 8 configure `python` differently and as `ansible` is written in `python` is is good to build a familiarity with the basics of how `python` works.
If you are curious as to what Operating Systems are in use try the following `ansible` *Ad-Hoc* command:

[source,sh]
----
ansible all -a "cat /etc/redhat-release"
----

.Sample Output
[source,texinfo]
----
hursday 07 January 2021  15:47:43 +0000 (0:00:00.038)       0:00:00.038 ****** 
appdb1 | CHANGED | rc=0 >>
Red Hat Enterprise Linux Server release 7.7 (Maipo)
app-01 | CHANGED | rc=0 >>
Red Hat Enterprise Linux release 8.2 (Ootpa)
app-02 | CHANGED | rc=0 >>
Red Hat Enterprise Linux release 8.2 (Ootpa)
frontend | CHANGED | rc=0 >>
Red Hat Enterprise Linux release 8.2 (Ootpa)
Thursday 07 January 2021  15:47:44 +0000 (0:00:00.679)       0:00:00.717 ****** 
=============================================================================== 
command ------------------------------------------------------------------------------------------------------------------------------------------------------------- 0.68s
Playbook run took 0 days, 0 hours, 0 minutes, 0 seconds
----

====

=== Next Steps

Now your environment is fully configured and ready to run.
Move onto link:03-ansible-refactoring-first-deploy.html[Part 2: First Deploy]

